### ISSUE TITLE
Printer name is not visible in Settings menu

### ISSUE THREAD

**Issue by bmelim** [loociano/MPSM2NetworkPrinting#4] opened 2020-06-01 11:16 UTC
Once printer is installed, menu item for said printer is missing. 

![image](https://user-images.githubusercontent.com/28276685/83403948-98944d80-a401-11ea-95f5-b25cdf89065b.png)

**Comment by loociano** [comment] 2020-06-01 22:48
Thanks @bmelim for reporting this issue!

I was able to reproduce and resolve.

The issue was introduced in 0.1.0 when the feature to rename printers was introduced. The feature removed `group_name` to be able to rename them freely, which broke the listing in Settings. Cura expects networked printers to have a `group_name` that does not change.

To accommodate users that may have more than one Monoprice V2 printer and need to easily distinguish them in the UI, printer names are now fixed to `MPSM V2 <IP address>`.

![](https://user-images.githubusercontent.com/742368/83462136-56e7bf00-a462-11ea-8b8a-6c9543f81891.png)

Fix has been included in releases 0.1.1 and 0.2.1.

**Closed** 2020-06-01 22:50 UTC
Labels: bug

**Comment by cptSwing** [comment] 2021-11-05 19:15
This however makes me have to re-add and re-config my printer each and every time the IP changes (2-3 times a week I guess)..

**Comment by loociano** [comment] 2021-11-06 20:52
Thanks for your comment @cptSwing. Indeed, the plugin assumes the IP address assigned to the printer is fixed.

The plugin can only know about printers by their (manually entered) IP address. It is expected that, if a printer changes its IP address, the plugin will not be able to connect to it anymore. The printer would need to be re-added with their new IP address.

@cptSwing I haven't heard about this problem before. Anecdotically, the IP address assigned to my printer never changes. As a workaround, is there a way you could configure your router to assign the same address to your printer?

**Comment by cptSwing** [comment] 2021-11-11 12:35
Mine kept moving between *.159 and *.160, we use DHCP in our wifi. I then used *M552* GCode to (hopefully) set *.159 to a fixed IP, saved to EEPROM, and it seems to be sticking for now.

**Comment by cptSwing** [comment] 2021-11-17 10:04
> 
> 
> Mine kept moving between *.159 and *.160, we use DHCP in our wifi. I then used _M552_ GCode to (hopefully) set *.159 to a fixed IP, saved to EEPROM, and it seems to be sticking for now.

For posterity's sake, it didn't stick - I'll just live with having 3 or 4 different-yet-same MPSMv2 profiles (one per IP). Navigating Cura's profile system is painful anyway, so this doesn't make a difference really ;)
