### ISSUE TITLE
Plugin does not load in newest cura version (5.0.0+)

### ISSUE THREAD

**Issue by joeybab3** [loociano/MPSM2NetworkPrinting#17] opened 2022-05-29 20:22 UTC
![image](https://user-images.githubusercontent.com/2829457/170889950-7f40e4b3-31f3-498f-bf47-cf05938bea5b.png)

**Comment by joeybab3** [comment] 2022-05-31 01:28
Got ya, I assumed they had introduced some sort of breaking change and wasn't sure if you had known so I figured I'd file it just in case. Thanks!

**Comment by loociano** [comment] 2022-05-31 22:33
[Release 0.6.0](https://github.com/loociano/MPSM2NetworkPrinting/releases/tag/0.6.0) fixes this issue.

Sent release to Ultimaker for review. It should be available in a few days. 

In the meantime, @joeybab3 could you drag and drop the [`.curapackage`](https://github.com/loociano/MPSM2NetworkPrinting/releases/download/0.6.0/MPSM2NetworkPrinting-0.6.0.curapackage)  to Cura to manually install the newest version? Let me know if the plugin works for you then.

**Comment by joeybab3** [comment] 2022-05-31 23:09
![image](https://user-images.githubusercontent.com/2829457/171298253-b53da5e2-d0d9-4ab3-8027-3c24882fce33.png)
Doesn't seem to be able to find the printer unfortunately

**Comment by joeybab3** [comment] 2022-05-31 23:11
![image](https://user-images.githubusercontent.com/2829457/171298533-c33270c8-bf54-48b4-b67e-60aaa2ee1d80.png)
Oddly enough it does work in cura 4.13.1 though

**Comment by loociano** [comment] 2022-06-02 06:32
Thanks @joeybab3, I am able to reproduce. Let me figure out why it does not work.

**Comment by MacPro-de** [comment] 2022-06-27 13:25
I cannot add a new printer in Cura 5.0.0 with plugin version 0.6.0, but a printer, that was already added and configured in Cura 4.x (with an earlier version of the plugin) seems to work, as soon as I install the 0.6.0 plugin in Cura 5.0.0 and activate it.

![Cura5MPSM](https://user-images.githubusercontent.com/77443523/175952377-5078b6f9-834b-44ba-b3c1-977b66cc704e.png)

**Comment by MacPro-de** [comment] 2022-06-27 13:33
Because it is a pre-release you would have to download it from here and install it manually.

**Comment by loociano** [comment] 2022-11-03 22:46
@iSteffen I don't know what went wrong but version 0.6.0 was never published in the marketplace, I sent today a newer one 0.7.0 for review. It should be hopefully published in a few days.

**Comment by loociano** [comment] 2022-11-04 00:16
@joeybab3 apologies for the delay. Fixed the issue and released 0.7.2. Could you manually install and verify if the issue persist on your end?

**Comment by Novae7** [comment] 2022-11-04 08:54
With 0.7.2 i also can add the printer to cura 5.2.1 :)
(Which didnt work before with 0.6.0 and 0.7.1)

**Comment by loociano** [comment] 2022-11-04 08:59
> With 0.7.2 i also can add the printer to cura 5.2.1 :) (Which didnt work before with 0.6.0 and 0.7.1)

Great! I'm closing this issue once 0.7.2 is published on the marketplace 👍

**Comment by loociano** [comment] 2022-11-08 21:00
Ultimaker had approved 0.6.0 but I forgot to publish to the marketplace 🤦‍♂️ 🤦‍♂️ [It is now published](https://marketplace.ultimaker.com/app/cura/plugins/loociano/MPSM2NetworkPrinting) (to be fair, it took them 15 days and I did not get any notification).

Waiting them to approve 0.7.2.

**Comment by loociano** [comment] 2022-11-23 09:57
[0.7.2 is now available in the Marketplace](https://marketplace.ultimaker.com/app/cura/plugins/loociano/MPSM2NetworkPrinting).

**Closed by loociano** 2022-11-23 09:57 UTC
Labels: bug
