### ISSUE TITLE
V1 stuck on downloaded when printing same file again

### ISSUE THREAD

**Issue by olywrestle** [loociano/MPSM2NetworkPrinting#8] opened 2020-06-05 13:45 UTC
If I try and send the same file name/project again to the printer (V1) then on the printer screen it gets stuck on "downloaded" and will never start the print project.

**Comment by loociano** [comment] 2020-06-05 21:35
Hi @olywrestle, thanks for reporting this issue.

I am unable to reproduce. I transferred a model wirelessly, cancelled the print, and transferred the same model again 3 or 4 more times; the printer behaved as expected.

What version of the plugin are you using? 
What's your printer's firmware version?

**Comment by loociano** [comment] 2020-06-26 22:12
@olywrestle is this issue still occurring in newer versions?

**Comment by loociano** [comment] 2020-07-11 22:04
Closing for now. Please reopen if the issue persists.

**Closed by loociano** 2020-07-11 22:04 UTC
Labels: bug
