### ISSUE TITLE
[V1] Target extruder temperature not set at start

### ISSUE THREAD

**Issue by olywrestle** [loociano/MPSM2NetworkPrinting#6] opened 2020-06-02 21:54 UTC
I did do a test to see if it worked with a V1. Following your instructions I was able to send the file to the printer. From what I could tell it uploaded the baseplate temp setting, but not the extruder. I had to set this manually. Once I manually set extruder temp, it printed normally.

Also, it only identifies as a V2 in Cura, even though I am using a V1.

**Comment by loociano** [comment] 2020-06-03 21:53
Thank @olywrestle for testing the plugin on a V1!

> it uploaded the baseplate temp setting, but not the extruder

This is an issue I noticed with Monoprice printers. Sometimes the target extruder temperature is not set right at the start, it is set a few minutes after when the bed temperature has reached its target. I am unsure what causes this.

Could you transfer a model with the plugin, then insert the SD card on a PC and open **cache.gc** with a text editor? 

The first lines should contain commands `M104` (set extruder temperature) and `M109` (wait for extruder temperature). For example:
```
;FLAVOR:Marlin
...
M140 S65
M105
M190 S65
M104 S215
M105
M109 S215
```

This would indicate that the commands to set the extruder temperature were transferred successfully and the issue is caused by the printer, its firmware or the SD card. 

> Also, it only identifies as a V2 in Cura, even though I am using a V1.

This is expected. Monoprice printers do not facilitate their version via Wi-Fi so it defaults to V2, which is the printer I own. Given that V1 is supported I should update this identifier to _Monoprice Select Mini_. :-)

**Comment by olywrestle** [comment] 2020-06-05 13:36
@loociano  your statement, "Sometimes the target extruder temperature is not set right at the start, it is set a few minutes after when the bed temperature has reached its target. I am unsure what causes this."  is 100% correct. That is what happeneed. Just so you have the info, here is the output of cache.gc

M140 S55
M105
M190 S55
M104 S210
M105
M109 S210

**Comment by loociano** [comment] 2020-06-05 14:46
Thanks. That indicates the commands which set temperatures were transferred successfully over the network.

Can you try the following?
1. On Cura, transfer a model wirelessly
2. Cancel the print from Cura or printer
3. From the printer, print 'cache.gc'.

Is the target extruder temperature set immediately or is there still some significant delay?

**Comment by loociano** [comment] 2020-06-26 22:09
Since release 0.5.0, the plugin forces preheating bed and extruder after uploading, to provide a consistent experience.

**Closed by loociano** 2020-06-26 22:09 UTC
Labels: bug
